---
name: YAML Tutorial
on:
  push:
    branches: [main]

jobs:
  build:
    name: Builder Job section
    runs-on: ubuntu-latest
    needs: [dev]
    steps:
      - name: Build and deploy on cloud
        run: echo "Building the application"

  dev:
    name: Development
    runs-on: windows-latest
    steps:
      - name: Run the Developer
        run: echo "Running the developer"

  Test:
    name: Testing the application
    runs-on: ubuntu-latest
    needs: [build, dev]
    steps:
      - name: Testing the application
        run: echo "Testing the application"
